fix: have coinit_flags match pythoncom with pyinstaller
program only crashed with this error when build with pyinstaller
runtimeerror: cannot change thread mode after it is set.
fixed by setting coinit_flags = 0 in a hook in pyinstaller